import { requireLittleLabelsAccess, consumeLittleLabelsQuota } from "../_shared/access.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const OPENAI_API_KEY = Deno.env.get("OPENAI_API_KEY");
const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function outputText(result:any):string{return result?.output?.flatMap((item:any)=>item.content||[])?.find((content:any)=>content.type==="output_text")?.text?.trim()||""}
async function makeWording(items:string[]){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.4-mini",input:[{role:"user",content:[{type:"input_text",text:`Create preschool classroom bin-label wording for these materials:\n\n${items.map((x,i)=>`${i+1}. ${x}`).join("\n")}\n\nFor each item:\n- concise child-friendly English label\n- natural concise Spanish translation\n- preserve recognizable brand/product names when appropriate\nReturn JSON only.`}]}],text:{format:{type:"json_schema",name:"batch_labels",strict:true,schema:{type:"object",additionalProperties:false,properties:{items:{type:"array",items:{type:"object",additionalProperties:false,properties:{english:{type:"string"},spanish:{type:"string"}},required:["english","spanish"]}}},required:["items"]}}}})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Wording request failed.");const text=outputText(result);if(!text)throw new Error("No label wording was returned.");return JSON.parse(text).items||[]}
async function makeProductWording(productTitle:string){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Authorization":`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.4-mini",input:[{role:"user",content:[{type:"input_text",text:`You are preparing a bilingual preschool classroom bin label from an exact retailer product title.\n\nExact product title: ${productTitle}\n\nKeep the English product name faithful and create a concise natural Spanish translation. Return JSON only.`}]}],text:{format:{type:"json_schema",name:"product_label",strict:true,schema:{type:"object",additionalProperties:false,properties:{english:{type:"string"},spanish:{type:"string"}},required:["english","spanish"]}}}})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Product wording request failed.");const text=outputText(result);if(!text)throw new Error("No product wording was returned.");return JSON.parse(text)}
async function generateImage(english:string){const response=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{"Authorization":`Bearer ${OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-image-2",prompt:`A clean realistic preschool classroom label photograph of ${english}. Show only the material itself, centered, isolated on a pure white background, no hands, no room background, no text. Easy for a preschool child to recognize.`,size:"1024x1024",quality:"low",output_format:"png"})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message||"Image generation failed.");const b64=result?.data?.[0]?.b64_json;if(!b64)throw new Error("No generated image was returned.");return `data:image/png;base64,${b64}`}
function absolutize(base:string,value:string){try{return new URL(value,base).toString()}catch{return""}}
function htmlDecode(value:string){return value.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim()}
function findProductInJson(value:any):any{if(!value)return null;if(Array.isArray(value)){for(const item of value){const f=findProductInJson(item);if(f)return f}return null}if(typeof value==="object"){const type=value["@type"];if(type==="Product"||(Array.isArray(type)&&type.includes("Product")))return value;if(value["@graph"]){const f=findProductInJson(value["@graph"]);if(f)return f}for(const child of Object.values(value)){const f=findProductInJson(child);if(f)return f}}return null}
function titleFromProductUrl(url:string){try{const u=new URL(url),parts=u.pathname.split("/").filter(Boolean),pIndex=parts.findIndex(x=>x.toLowerCase()==="p");let slug=pIndex>0?parts[pIndex-1]:(parts.at(-1)||"");return slug.replace(/\.(html?|aspx?)$/i,"").replace(/[-_]+/g," ").replace(/\b\w/g,m=>m.toUpperCase()).replace(/\s+/g," ").trim()}catch{return""}}
function lakeshoreProductInfo(url:string){try{const u=new URL(url);if(!/(^|\.)lakeshorelearning\.com$/i.test(u.hostname))return null;const m=u.pathname.match(/\/p\/([A-Za-z0-9-]+)\/?$/i);if(!m)return null;const sku=m[1];return{sku,imageUrl:`https://img.lakeshorelearning.com/is/image/OCProduction/${sku.toLowerCase()}?fmt=png&op_sharpen=0&op_usm=1.25,0.5,0,0&pscan=auto&qlt=90&resMode=sharp2&wid=1200`}}catch{return null}}
async function pageProduct(url:string){const page=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/124 Safari/537.36","Accept":"text/html,application/xhtml+xml","Accept-Language":"en-US,en;q=0.9"},redirect:"follow"});if(!page.ok)throw new Error(`Product page returned ${page.status}.`);const html=await page.text();let title="",image="";for(const match of [...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)]){try{const product=findProductInJson(JSON.parse(match[1].trim()));if(product){title=String(product.name||title||"").trim();const pi=product.image;if(typeof pi==="string")image=pi;else if(Array.isArray(pi)){const first=pi.find((x:any)=>typeof x==="string"||x?.url||x?.contentUrl);image=typeof first==="string"?first:(first?.url||first?.contentUrl||"")}else if(pi&&typeof pi==="object")image=pi.url||pi.contentUrl||"";if(title&&image)break}}catch{}}
if(!title)title=html.match(/<h1\b[^>]*>([\s\S]*?)<\/h1>/i)?.[1]?.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()||html.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)?.[1]||html.match(/<title[^>]*>([^<]+)<\/title>/i)?.[1]||"";if(!image)image=html.match(/<meta[^>]+property=["']og:image(?::secure_url)?["'][^>]+content=["']([^"']+)["']/i)?.[1]||html.match(/<link[^>]+rel=["']image_src["'][^>]+href=["']([^"']+)["']/i)?.[1]||"";return{title:htmlDecode(title.replace(/\s+/g," ").trim()),image:absolutize(url,htmlDecode(image))}}
async function imageAsDataUrl(url:string){const res=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0"},redirect:"follow"});if(!res.ok)throw new Error("Product image could not be downloaded.");const type=res.headers.get("content-type")||"image/jpeg",buf=new Uint8Array(await res.arrayBuffer());if(buf.byteLength>6_000_000)throw new Error("Product image is too large.");let binary="";for(let i=0;i<buf.length;i+=0x8000)binary+=String.fromCharCode(...buf.subarray(i,Math.min(i+0x8000,buf.length)));return `data:${type};base64,${btoa(binary)}`}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});
const accessDenied = await requireLittleLabelsAccess(req); if (accessDenied) return accessDenied;
try{if(!OPENAI_API_KEY)throw new Error("OPENAI_API_KEY is not configured.");const body=await req.json(),mode=body?.mode;if(mode==="list"||mode==="list_wording"){const items=Array.isArray(body.items)?body.items.map((x:unknown)=>String(x).trim()).filter(Boolean).slice(0,25):[];if(!items.length)return json({error:"At least one list item is required."},400);const quotaDenied=await consumeLittleLabelsQuota(req,'text');if(quotaDenied)return quotaDenied;const wording=await makeWording(items);return json({success:true,items:wording.map((w:any,i:number)=>({english:w?.english||items[i]||"Material",spanish:w?.spanish||"",photo_data:"",image_source:"pending",notes:""}))})}
if(mode==="url"){const url=String(body?.url||"").trim();if(!/^https?:\/\//i.test(url))return json({error:"A valid product URL is required."},400);const quotaDenied=await consumeLittleLabelsQuota(req,'text');if(quotaDenied)return quotaDenied;let pageTitle="",pageImage="",note="";const lakeshore=lakeshoreProductInfo(url);try{const page=await pageProduct(url);pageTitle=page.title;pageImage=page.image}catch(err){note=err instanceof Error?err.message:"Product page could not be read."}if(lakeshore?.imageUrl)pageImage=lakeshore.imageUrl;const urlTitle=titleFromProductUrl(url),authoritativeName=pageTitle||urlTitle||(lakeshore?.sku?`Lakeshore product ${lakeshore.sku}`:"classroom material"),productWording=await makeProductWording(authoritativeName),english=productWording?.english||authoritativeName,spanish=productWording?.spanish||"";let photo_data="",image_source="missing",needs_product_image=true;if(pageImage){try{photo_data=await imageAsDataUrl(pageImage);image_source="product";needs_product_image=false}catch(err){note+=(note?" ":"")+(err instanceof Error?err.message:"Product image could not be downloaded.")}}return json({success:true,items:[{english,spanish,photo_data,image_source,needs_product_image,notes:note}]})}
if(mode==="image"){const english=String(body?.english||"").trim(),spanish=String(body?.spanish||"").trim();if(!english)return json({error:"English wording is required."},400);const quotaDenied=await consumeLittleLabelsQuota(req,'picture');if(quotaDenied)return quotaDenied;const photo_data=await generateImage(english);return json({success:true,items:[{english,spanish,photo_data,image_source:"generated",notes:""}]})}return json({error:"Unknown batch-label mode."},400)}catch(error){return json({success:false,error:error instanceof Error?error.message:"Batch label creation failed."},500)}});
