// Synthetic activated customer, production controls, no live account or provider I/O.
const {chromium,webkit,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),engine=process.env.BROWSER_ENGINE||'chromium',out=path.join(root,'test-results/audit',engine);
fs.mkdirSync(out,{recursive:true});
(async()=>{
 const server=http.createServer((req,res)=>{try{const p=new URL(req.url,'http://local').pathname,file=path.resolve(root,'.'+(p==='/'?'/index.html':p));if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.png')?'image/png':file.endsWith('.webmanifest')?'application/manifest+json':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;let browser;
 try{
  browser=await({chromium,webkit})[engine].launch({headless:true});
  for(const width of [390,768,1280]){
   const context=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'}),page=await context.newPage();page.setDefaultTimeout(20000);
   const errors=[],provider=[],unexpected=[],writes=[],db={labels:new Map(),print_queue:new Map()};let releaseAuth;const auth=new Promise(r=>releaseAuth=r);
   const session={access_token:'synthetic-activated-customer',refresh_token:'synthetic-refresh',expires_in:3600,user:{id:'synthetic-customer',is_anonymous:false,email:'fixture@example.invalid',identities:[{}]}};
   page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.dismiss());
   await page.addInitScript(s=>{localStorage.setItem('littleLabelsWelcomeSeenV1','1');localStorage.setItem('eea_label_maker_supabase_session_v1',JSON.stringify(s));window.__printed=0;window.print=()=>window.__printed++;},session);
   await context.route('**/*',async route=>{
    const req=route.request(),u=new URL(req.url());if(u.origin===origin)return route.continue();
    const json=(body,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
    if(u.hostname!=='ctmqvbsjliinlddfolti.supabase.co'){unexpected.push(u.origin+u.pathname);return route.abort();}
    if(u.pathname.includes('/auth/')){await auth;return json(session);}
    if(u.pathname.endsWith('/little_labels_access_status'))return json({active:true});
    if(u.pathname.endsWith('/little_labels_admin_status'))return json({is_admin:false});
    if(u.pathname.includes('/functions/')){provider.push(u.pathname);return json({success:false,error:'Provider calls forbidden in this manual fixture'},403);}
    const table=u.pathname.split('/').pop();if(!db[table]){unexpected.push(u.pathname);return route.abort();}
    const matches=row=>{for(const [key,value] of u.searchParams){if(['select','order','on_conflict'].includes(key))continue;if(value==='is.null'){if(row[key]!=null)return false;continue;}if(value.startsWith('eq.')){let expected=value.slice(3);if(expected.startsWith('"'))expected=JSON.parse(expected);if(String(row[key])!==String(expected))return false;}}return true;};
    if(req.method()==='POST'){const rows=req.postDataJSON();writes.push({table,method:'POST',ids:rows.map(r=>r.id)});for(const row of rows)if(!db[table].has(row.id))db[table].set(row.id,{...row});return json([]);}
    if(req.method()==='PATCH'){const updated=[];writes.push({table,method:'PATCH',body:req.postDataJSON()});for(const row of db[table].values())if(matches(row)){Object.assign(row,req.postDataJSON());updated.push({...row});}return json(updated);}
    assert.equal(req.method(),'GET','No delete or unplanned database operation');return json([...db[table].values()].filter(matches));
   });
   const shot=async name=>{await page.waitForFunction(()=>[...document.querySelectorAll('img')].filter(x=>x.getBoundingClientRect().width&&x.getBoundingClientRect().height&&x.getAttribute('src')).every(x=>x.complete&&x.naturalWidth));await page.screenshot({path:path.join(out,`${width}-${name}.png`),fullPage:true});};
   const checkLayout=async selector=>{assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);assert.equal(await page.locator(selector).evaluate(x=>x.scrollWidth<=x.clientWidth+1),true);};
   try{
    await page.goto(origin,{waitUntil:'domcontentloaded'});await expect(page.locator('#llaCheckingTitle')).toHaveText('Opening Little Labels…');await expect(page.locator('#llaAccountPane')).toBeHidden();await shot('loading');releaseAuth();await page.waitForFunction(()=>cloudReady&&cloudLoaded&&LittleLabelsAccess.isActive());await expect(page.locator('#llAccessGate')).toBeHidden();await page.waitForTimeout(850);await shot('home');
    assert.equal(await page.locator('.home-action .home-icon svg').count(),6);await checkLayout('#home');
    await page.locator('#homeTypeBtn').click();await page.locator('#tlEnglish').fill('QA Blocks');await page.locator('#tlNext').click();await page.locator('#chooseSetBtn').click();await page.locator('#addToQueue').click();await expect(page.locator('#queue')).toBeVisible();assert.equal(db.labels.size,1);assert.equal(db.print_queue.size,2);assert.ok([...db.labels.values()].every(x=>x.spanish===''));
    await page.locator('#queueBack').click();await page.locator('#libraryBtn').click();await page.getByRole('button',{name:'Edit label QA Blocks',exact:true}).click();await page.locator('#lleEnglish').fill('QA Counting Blocks');await shot('library-editor');await page.locator('#lleSave').click();await expect(page.locator('#llLibraryEditor')).toBeHidden();assert.equal([...db.labels.values()][0].english,'QA Counting Blocks');assert.ok([...db.print_queue.values()].every(x=>x.english==='QA Blocks'));
    await page.getByRole('button',{name:'Edit label QA Counting Blocks',exact:true}).click();await page.locator('#lleEnglish').fill('QA Separate Copy');await page.locator('#lleCopy').dblclick();await expect(page.locator('#llLibraryEditor')).toBeHidden();assert.equal(db.labels.size,2);assert.equal(db.print_queue.size,2);
    await page.locator('#libraryBack').click();await page.locator('#homeListBtn').click();assert.equal(await page.locator('#makeList h2:visible').count(),1);await page.locator('#makeListInput').fill('QA Pencils\nQA Paper');await page.locator('#makeListCreateBtn').click();await expect(page.locator('.mli-preview').first()).toBeHidden();await expect(page.locator('.mli-time-note')).toBeHidden();
    const photo=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=300;c.height=200;const x=c.getContext('2d');x.fillStyle='#f3edda';x.fillRect(0,0,300,200);x.fillStyle='#5d8fab';x.fillRect(50,50,90,90);return c.toDataURL('image/png')});
    const choose=page.waitForEvent('filechooser');await page.locator('[data-upload="0"]').click();await(await choose).setFiles({name:'synthetic.png',mimeType:'image/png',buffer:Buffer.from(photo.split(',')[1],'base64')});await expect(page.locator('.mli-preview img')).toHaveCount(1);await page.locator('#mliTranslation-0').fill('Manual wording');await shot('list-manual-photo');await checkLayout('#mlIsolated');await page.locator('#mliPrint').click();await expect(page.locator('#queue')).toBeVisible();assert.equal(db.labels.size,4);assert.equal(db.print_queue.size,4);
    await page.locator('#queueBack').click();await page.getByRole('button',{name:/Name Labels/}).click();await page.locator('#nlNames').fill('QA Ada\nQA Bea');await page.getByRole('button',{name:'Name + Photo',exact:true}).click();await page.locator('#nlNextStudent').click();await expect(page.locator('#nlPreviewPosition')).toContainText('QA Bea');await page.locator('#nlNext').click();await expect(page.locator('#nlMissingPhotos')).toBeVisible();assert.equal(db.labels.size,4);await shot('missing-photos');await page.locator('#nlAddMissingPhotos').click();await expect(page.locator('#nlMissingPhotos')).toBeHidden();await page.locator('#nlNext').click();await page.locator('#nlContinueNameOnly').click();await expect(page.locator('#queue')).toBeVisible();assert.equal(db.labels.size,6);assert.equal(db.print_queue.size,6);assert.ok([...db.labels.values()].filter(x=>/^QA (Ada|Bea)$/.test(x.english)).every(x=>!x.photo_data));
    await page.locator('#queueBack').click();await page.locator('#libraryBtn').click();await page.getByRole('button',{name:'Reprint QA Counting Blocks',exact:true}).click();await expect(page.locator('#llReprintSummary')).toContainText('2 copies');await page.locator('#llReprintSets [data-single-choice]').click();await expect(page.locator('#reprintQueueBtn')).toHaveText('Add 1 Copy to Print');await shot('reprint-count');await page.locator('#reprintQueueBtn').click();await expect(page.locator('#queue')).toBeVisible();assert.equal(db.print_queue.size,7);assert.equal(db.labels.size,6);
    await page.locator('#mockSheets').click();await expect(page.locator('#printPreview')).toBeVisible();await page.waitForFunction(()=>[...document.querySelectorAll('#sheetPreviewPages img')].length>0&&[...document.querySelectorAll('#sheetPreviewPages img')].every(x=>x.complete&&x.naturalWidth));await shot('print-preview');await page.locator('#printNowBtn').click();await page.waitForFunction(()=>__printed===1);assert.equal(db.print_queue.size,7);
    let pdf=null;if(engine==='chromium'&&width===1280){const bytes=await page.pdf({path:path.join(out,'audit-letter.pdf'),preferCSSPageSize:true,printBackground:true});const raw=bytes.toString('latin1');assert.match(raw,/\/MediaBox\s*\[\s*0\s+0\s+612(?:\.0+)?\s+792(?:\.0+)?\s*\]/);pdf={bytes:bytes.length,letterMediaBox:true};}
    await page.locator('#printPreviewBack').click();await page.locator('#queueBack').click();await page.locator('#littleLabelsSettingsBtn').click();await expect(page.locator('#llsSettingsStatus')).toContainText('do not sync across devices');await page.keyboard.press('Escape');await expect(page.locator('#llSettings')).toBeHidden();await expect(page.locator('#littleLabelsSettingsBtn')).toBeFocused();
    const clipping=await page.evaluate(async image=>{const calls=[],base=CanvasRenderingContext2D.prototype.fillText;CanvasRenderingContext2D.prototype.fillText=function(text,...args){calls.push(String(text));return base.call(this,text,...args)};const english='A classroom collection of carefully sorted building materials for collaborative planning and creative construction FINALWORD';try{const raster=await rasterizeFinishedLabel({english,spanish:'',photo:image,size:'Business Card · 3.375 × 2 in'});return {english,drawn:calls,finalWordDrawn:calls.some(x=>x.includes('FINALWORD')),raster}}finally{CanvasRenderingContext2D.prototype.fillText=base}},photo);
    if(clipping.raster){const match=clipping.raster.match(/^data:image\/(png|jpeg);base64,(.+)$/);if(match)fs.writeFileSync(path.join(out,`${width}-long-caption.${match[1]==='jpeg'?'jpg':'png'}`),Buffer.from(match[2],'base64'));delete clipping.raster;}
    assert.deepEqual(provider,[]);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,`${width}-results.json`),JSON.stringify({engine,width,passed:true,errors,provider,writes,blockedExternal:unexpected,pdf,clipping},null,2));console.log(`PASS ${engine} ${width}px library edits/copies, base manual uploads/names, exact reprints, decoded print and modal keyboard; clipping diagnostic=${clipping.finalWordDrawn}`);
   }catch(e){releaseAuth();await page.screenshot({path:path.join(out,`${width}-FAILURE.png`),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,`${width}-failure.json`),JSON.stringify({error:e.stack,errors,provider,writes},null,2));throw e;}finally{await context.close();}
  }
 }finally{await browser?.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
