const {fixture,tick}=require('./audit-fixture.cjs'),assert=require('node:assert/strict');
async function settle(){await tick();await tick();}
async function seed(f){f.w.eval("library=[{id:'synthetic-master',english:'Saved Blocks',spanish:'',photo:''}];queue=[];refreshLibrary();openReprint(library[0]);");await settle();}
(async()=>{
 const f=await fixture(false);let stored;
 try{
  await seed(f);assert.match(f.$('llReprintSummary').textContent,/2 copies/);assert.equal(f.$('reprintQueueBtn').textContent,'Add 2 Copies to Print');f.$('reprintQueueBtn').click();f.$('reprintQueueBtn').click();await settle();assert.equal(f.w.eval('queue.length'),2);assert.equal(f.w.eval('library.length'),1);
  const settings=f.w.LittleLabelSettings.get();settings.sets.push({id:'synthetic-three',name:'Three copies',items:[['business',2],['cp',1]]});f.w.localStorage.setItem('littleLabelsSettingsV3',JSON.stringify(settings));f.w.dispatchEvent(new f.w.Event('little-label-settings-changed'));f.w.eval('openReprint(library[0])');await settle();f.w.document.querySelector('#llReprintSets [data-combination-id="synthetic-three"]').click();assert.match(f.$('llReprintSummary').textContent,/3 copies/);f.$('reprintQueueBtn').click();await settle();assert.equal(f.w.eval('queue.length'),5);assert.equal(f.w.eval('library.length'),1);assert.equal(f.w.eval('queue.filter(x=>x.size.includes("Fold-Over")).length'),1);
  f.w.eval('openReprint(library[0])');await settle();assert.equal(f.w.document.querySelector('#llReprintSets [data-combination-id="synthetic-three"]').getAttribute('aria-pressed'),'true');f.w.document.querySelector('#llReprintSets [data-single-choice]').click();assert.match(f.$('llReprintSummary').textContent,/1 copy/);f.$('reprintQueueBtn').click();await settle();assert.equal(f.w.eval('queue.length'),6);assert.equal(f.ai().length,0);assert.deepEqual(f.errors,[]);stored={'littleLabelsReprintChoiceV1':f.w.localStorage.getItem('littleLabelsReprintChoiceV1')};console.log('PASS visible reprint counts, exact 2/3/1 copies, repeated-click guard and unchanged masters');
 }finally{f.close()}
 const next=await fixture(false,stored);try{await seed(next);assert.equal(next.w.document.querySelector('#llReprintSets [data-single-choice]').getAttribute('aria-pressed'),'true');assert.match(next.$('llReprintSummary').textContent,/1 copy/);assert.deepEqual(next.errors,[]);console.log('PASS reprint choice survives browser reload without changing saved labels');}finally{next.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
