const {JSDOM,ResourceLoader,VirtualConsole}=require('jsdom');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
class Local extends ResourceLoader{fetch(url){const u=new URL(url);return u.hostname==='labels.test'&&u.pathname.endsWith('.js')?Promise.resolve(fs.readFileSync(path.join(root,u.pathname))):null}}
(async()=>{
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>{if(!e.message.includes('navigation')&&!e.message.includes('window.scrollTo'))errors.push(e.message)});
 const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://labels.test/',pretendToBeVisual:true,runScripts:'dangerously',resources:new Local(),virtualConsole:vc,beforeParse(w){w.fetch=async()=>{throw Error('Synthetic offline')};w.scrollTo=()=>{};w.alert=()=>{};w.TextEncoder=TextEncoder;w.Image=class{constructor(){this.naturalWidth=1;this.naturalHeight=1}set src(s){queueMicrotask(()=>this.onload?.())}};w.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},drawImage(){}});w.HTMLCanvasElement.prototype.toDataURL=()=> 'data:image/jpeg;base64,c3ludGhldGlj';}});
 const w=dom.window;await new Promise(r=>w.addEventListener('load',r));await new Promise(r=>setTimeout(r,10));const $=id=>w.document.getElementById(id),click=id=>$(id).click(),input=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new w.Event('input'))},tick=()=>new Promise(r=>setTimeout(r,5));
 try{
 assert.equal($('homeSyncStatus').textContent,'Session only');
 input('makeListInput','Synthetic Blocks\nSynthetic Pencils');click('makeListCreateBtn');assert.ok($('mliSave'));const first=w.document.querySelector('.mli-en');first.value='Synthetic Edited';first.dispatchEvent(new w.Event('input'));click('mliBack');click('makeListCreateBtn');assert.equal(w.document.querySelector('.mli-en').value,'Synthetic Edited');click('mliPrint');click('mliPrint');await tick();assert.equal(w.eval('queue.length'),2);assert.equal(w.eval('library.length'),2);assert.equal(w.eval('queue[0].english'),'Synthetic Edited');console.log('PASS list completion, retained edits, repeat click');
 input('makeListInput','Synthetic Library');click('makeListCreateBtn');click('mliSave');await tick();assert.equal(w.eval('queue.length'),2);assert.equal(w.eval('library.length'),3);console.log('PASS library-only save');
 input('nlNames','Synthetic Student');w.document.querySelector('[data-style="photo"]').click();w.FileReader=class{readAsDataURL(){this.result='data:image/png;base64,c3ludGhldGlj';this.onload()}};const create=w.document.createElement.bind(w.document);w.document.createElement=(tag)=>{const el=create(tag);if(tag==='input'){el.click=()=>{Object.defineProperty(el,'files',{value:[{}]});el.onchange()}}return el};w.document.querySelector('#nlPhotos button').click();w.document.createElement=create;$('nlCopies').value='2';click('nlNext');await tick();assert.equal(w.eval('queue.length'),4);assert.ok(w.eval('queue.slice(2).every(x=>x.photo.startsWith("data:"))'));assert.equal(w.eval('library.length'),4);console.log('PASS name-photo state and copies reach queue/library');
 $('mlIsolated').classList.remove('mli-hidden');$('nameLabelsOverlay').classList.remove('hide');$('llAccessGate').classList.remove('lla-hidden');w.show('account');assert.ok($('mlIsolated').classList.contains('mli-hidden'));assert.ok($('nameLabelsOverlay').classList.contains('hide'));assert.ok($('llAccessGate').classList.contains('lla-hidden'));w.show('home');assert.ok(!$('llAccessGate').classList.contains('lla-hidden'));console.log('PASS honest offline status and account return restores purchase gate');
 const statuses=await w.eval(`(async()=>{currentUser={id:'status-owner',is_anonymous:false,email:'synthetic@example.invalid'};cloudReady=true;cloudSession={access_token:'synthetic-token'};updateAccountUI();let rejectWrite;fetch=async(url,options)=>{if(options.method==='POST')return new Promise((_,reject)=>rejectWrite=reject);return {ok:true,status:200,json:async()=>[]}};const options={method:'POST',body:'[{"id":"synthetic"}]'};const saving=restFetch('labels',options,false).catch(()=>{});await loadCloudData();const pending=document.getElementById('homeSyncStatus').textContent;rejectWrite(Error('Synthetic failed write'));await saving;await loadCloudData();updateAccountUI();const failed=document.getElementById('homeSyncStatus').textContent,sub=document.getElementById('accountStatusSub').textContent;fetch=async()=>({ok:true,status:200,json:async()=>[]});await restFetch('labels',options,false);await loadCloudData();return [pending,failed,sub,document.getElementById('homeSyncStatus').textContent]})()`);assert.equal(statuses[0],'Saving…');assert.equal(statuses[1],'Sync unavailable');assert.ok(!statuses[2].includes('is connected'));assert.equal(statuses[3],'Cloud connected');console.log('PASS concurrent sync status and sticky failed-write recovery');
 const ownershipStatus=await w.eval(`(async()=>{currentUser={id:'pending-A'};cloudReady=true;cloudSession={access_token:'synthetic-A'};updateAccountUI();let finishOld;fetch=async(url,options)=>options.method==='POST'?new Promise(resolve=>finishOld=resolve):({ok:true,status:200,json:async()=>[]});const old=restFetch('labels',{method:'POST',body:'[{"id":"old"}]'},false);currentUser={id:'pending-B'};cloudSession={access_token:'synthetic-B'};updateAccountUI();await loadCloudData();const before=document.getElementById('homeSyncStatus').textContent;finishOld({ok:true,status:200,json:async()=>[]});await old.catch(error=>{if(error.code!=='SESSION_CHANGED')throw error});return [before,document.getElementById('homeSyncStatus').textContent]})()`);assert.deepEqual(Array.from(ownershipStatus),['Cloud connected','Cloud connected']);console.log('PASS sync counters belong only to the current account');
 w.__actualRestFetch=w.restFetch;
 const crossover=await w.eval(`(async()=>{currentUser={id:'synthetic-A'};cloudReady=true;cloudSession={access_token:'token-A',refresh_token:'refresh-A'};const calls=[];fetch=async(url,options)=>{calls.push(options.headers.Authorization);currentUser={id:'synthetic-B'};cloudSession={access_token:'token-B',refresh_token:'refresh-B'};return {status:401,ok:false,json:async()=>({message:'Synthetic expired token'})}};const job=LittleLabelWorkflowSave.create([{english:'Synthetic Private',photo:'',spanish:''}],['Business Card']);try{await LittleLabelWorkflowSave.save(job,true)}catch{}return calls})()`);assert.deepEqual(Array.from(crossover),['Bearer token-A']);console.log('PASS actual restFetch never retries old draft under a new session');
 const result=await w.eval(`(async()=>{currentUser={id:'synthetic-owner'};cloudReady=true;let fail=true;const labels=new Map(),printed=new Map(),calls=[];restFetch=async(p,o)=>{calls.push(p);const store=p.startsWith('labels')?labels:printed;for(const r of JSON.parse(o.body))store.set(r.id,r);if(p.startsWith('print_queue')&&fail){fail=false;throw Error('Synthetic lost response')}return []};loadCloudData=async()=>{};const api=LittleLabelWorkflowSave,job=api.create([{english:'Synthetic Retry',photo:'',spanish:''}],['Business Card']);let failed=false;try{await api.save(job,true)}catch{failed=true}await api.save(job,true);await api.save(job,true);const switched=api.create([{english:'Synthetic Private',photo:'',spanish:''}],['Business Card']);currentUser={id:'other-owner'};let blocked=false;try{await api.save(switched,true)}catch{blocked=true}return {failed,blocked,labelCount:labels.size,queueCount:printed.size,calls:calls.length}})()`);
 assert.deepEqual(JSON.parse(JSON.stringify(result)),{failed:true,blocked:true,labelCount:1,queueCount:1,calls:3});assert.deepEqual(errors,[]);console.log('PASS cloud payloads, lost-response retry deduplication, account isolation');
 }finally{w.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
