import { requireLittleLabelsAccess, consumeLittleLabelsQuota } from "../_shared/access.ts";
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const KEY=Deno.env.get("OPENAI_API_KEY");
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const names:Record<string,string>={es:"Spanish",fr:"French",ar:"Arabic",zh:"Chinese",vi:"Vietnamese",de:"German",it:"Italian",pt:"Portuguese",ko:"Korean",ja:"Japanese",ht:"Haitian Creole"};
function reply(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json"}})}
function text(r:any){return r?.output?.flatMap((x:any)=>x.content||[])?.find((x:any)=>x.type==="output_text")?.text?.trim()||""}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});
const accessDenied = await requireLittleLabelsAccess(req); if (accessDenied) return accessDenied;
try{const b=await req.json();const items=Array.isArray(b.items)?b.items.map((x:any)=>String(x).trim()).filter(Boolean).slice(0,25):[];if(!items.length)return reply({success:false,error:"Add at least one item."},400);const quotaDenied=await consumeLittleLabelsQuota(req,'text');if(quotaDenied)return quotaDenied;const code=String(b.language||b.target_language||"es").toLowerCase();const language=code==="none"?"":(names[code]||"Spanish");const prompt=`Make concise preschool classroom label wording for each item below. Keep the same order. ${language?`Also give a natural concise ${language} translation.`:"Do not translate."}\n\n${items.map((x:string,i:number)=>`${i+1}. ${x}`).join("\n")}`;const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5.4-mini",input:prompt,text:{format:{type:"json_schema",name:"labels",strict:true,schema:{type:"object",additionalProperties:false,properties:{items:{type:"array",items:{type:"object",additionalProperties:false,properties:{english:{type:"string"},translation:{type:"string"}},required:["english","translation"]}}},required:["items"]}}}})});const data=await res.json();if(!res.ok)throw Error(data?.error?.message||"Wording request failed.");const raw=text(data);if(!raw)throw Error("No wording returned.");const parsed=JSON.parse(raw);return reply({success:true,items:items.map((original:string,i:number)=>{const x=parsed.items?.[i]||{};return{english:x.english||original,translation:code==="none"?"":(x.translation||"")}})})}catch(e){return reply({success:false,error:e instanceof Error?e.message:"Could not create wording."},500)}});
